export const iconNames = [
  'Electron',
  'Express',
  'Github',
  'Javascript',
  'Jest',
  'LinkedIn',
  'NestJS',
  'Next.js',
  'Node.js',
  'Playwright',
  'React',
  'Redux',
  'Tailwind CSS',
  'Twitter',
  'Typescript',
  'Vite',
  'WebGL',
  'Webpack',
  'XState',
  'WebAssembly',
  'TensorFlow.js',
  'Styled-components',
  'Cypress',
  'jQuery',
  'Backbone.js',
  'Gulp.js',
  'Sass',
  'PHP',
  'MySQL',
  'Wordpress',
] as const;

export type IconType = (typeof iconNames)[number];
